HIFB_SRC +=drv/$(ARCH_DIR)/hifb_vou_drv.c
HIFB_SRC +=drv/$(ARCH_DIR)/hifb_blit.c
HIFB_SRC +=drv/$(ARCH_DIR)/hifb_vou_graphics.c
HIFB_SRC +=drv/$(ARCH_DIR)/hifb_graphics_drv.c
HIFB_SRC +=drv/$(ARCH_DIR)/hifb_graphic_hal.c
